version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        ports:
            - '5432:5432'
    mesh:
        image: 0xorg/mesh:11.0.3
        restart: on-failure
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            ETHEREUM_CHAIN_ID: '${CHAIN_ID}'
            ENABLE_GRAPHQL_SERVER: 'true'
            VERBOSITY: 3
        volumes:
            - ./0x_mesh_test:/usr/mesh/0x_mesh
        ports:
            - '127.0.0.1:60557:60557'
            - '127.0.0.1:60558:60558'
            - '127.0.0.1:60559:60559'
    0xapi:
        image: 0xapi:latest
        build:
            context: ./
            dockerfile: Dockerfile
        command: ["yarn", "start:db_migrate"]
        depends_on:
            - postgres
            - mesh
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        volumes:
            - .env_prod:/usr/src/app/.env
        ports:
            - 3000:3000
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            ETHEREUM_CHAIN_ID: '${CHAIN_ID}'
            POSTGRES_URI: 'postgresql://api:api@postgres/api'
            MESH_WEBSOCKET_URI: http://mesh:60557
            MESH_HTTP_URI: http://mesh:60557
